language: node_js
node_js:
- 0.12.0
after_script:
- npm run cover
- npm run codeclimate
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: simbo/validate-by-shorthand
env:
  global:
    secure: uD+Hu0IKLv2XC6U7qKwLJ1VwaB1GhCp8QPfrR2Fa2mbyi/B1fEeRCdr7rY4C0rHGw02aGxxg3IyT/IsN+cK/V/Xvn2lVTLamJdXjgsN7pomfFTOOVQSkI4XWZCAv8DNkZnj6apA/VoqFu4RTIg1RzIvE57MfhUWck4RDWcNiIAkGJdzjZl2dwWx6K3/O/2oSjvhWBXdBR8AkpqzVm3X8pSxge5Sz+sIiHlhzEOCOKx1Lvy9hLWDpl8D4vnL2XTG6Y/Y0WXRfu8d548YP5WpPVTCmFkawSTD4ka80I5jkvFndlw1Zz4ZIeMHKpQGkfi8CGTZngXaqRJB+zODlmWbE0pMCQZ0vEvI7sDoJhpZSRbOIKEGhnf6Hbtfv+swKtjfnjtqy52sdi3Pj6x0otvpl5LvIf2t8NBHswcPAIq2WLNZYgcNv9AWH/lNMSGKAHWPbSD0waLLYKCFZeY3i+zuy07+8qJRqQX2iCaXz/UxjQ0sS8CKUKu9lEB2wJmNVz9SCz0EtE4wOQEEEBgRZ1+lOtC+l/A/ivJeqMa/yrdw9+Fk+NvOs4I5nIZOmoBd+t/rdAas4fozmh2NdZxA619L615nHZnPT3wyREYZALCx77gEN1YT645rUb8jcBSNkve1a4TCPqALxZ3uJ0Grl6Gsl7OX2d6TmZarsK8HPJiSXOKw=
