language: node_js
node_js:
- 0.12.0
after_script:
- npm run cover
- npm run codeclimate
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: simbo/validate-anything
env:
  global:
  - secure: Q0w2HZqrHzgUTKUG1KBcnKjGssfYSOBcAZz4rjR1mzLnc29cmgR1GK2C4AOFa7EWlje+FKFMRU3CJz5+bvyaCe5n4YCuede0WeykB+gqjjp6u59OOmDkKtU5Q4cr4yZZawfipyLI+kdDndK5qaWaNyoSXViAScmUjhbNxnrHuE+LlSifUKVJom1tHzcowcKKatclffT86aYGigGzP5XFsdXZfk3EsKZHCoPewYgj9ohWocBF0r8RY2bvwbbXZUPOQak2k9dxG78eyX5PSwTlXMuMXaXwNnoCl4M7vMaXvh+SwXcnIRk7OrgLFjhrjROhF9iteX4DFnXQ4PuazJSpzjijFdLhrCXG62O4Cm0DpRwejv3gtfH7p/Lwew75r5GcSlJUvVslPuPaPGVSJZUKwrmvyfU2F0Z7d78Gkvb39lKzNMHHEzy3eBT3NTekknnWPmQvH3atfKe3Z2Q2Zm65wITYIgiYQNCzgpHt9YaPYVl6hAiIOCkbdKmr5CqUdlFuL6nwi5cS1PxUcLZgTBvKW1kRLhKJV+ipg8NasSmVFKHf/hi9/6wUhbEXCc2xMYX+Ar23LGrvTHwi9gh6Ljd+8uwcJzwaeC2zdm11/CoHwOxJDS5jAk409DQKCdWvweFtAKJNIGFw0ruTNemh23wObx1WVxjIsXVwhR/BWclM7ow=
  - secure: cA2rZX5pXKNvzjDH/u6VIGM4yKDKuwbzVPDvIaLtsaFcS1ik3Xr681atbcSz94YlKvqisH+MWcYxItg+7segIf0oU7w4l3Pi8FSDZXdGea5VUd95bjkYXumd48F4O/pEh9Sf87VsOUdAguajAmYHoFjq7Ve7LCwtkCk/UL4CPFWO6CEHEIARPETCLyePY1VbCXR0afjeZ9T1H5LQ+kspYwKUyhbZgZzX0+pBt99tj2N5J1fZtMbREqhiNDXYCqs7xgERRkAeE4KknNH/z0gkgk7/8Qk5+MBn9nz05E7DaWqzeNQU6rwGxL+0uerKipUtV8ux0076DPzeXLkdAMN3FQ2Pe+aZWNs8/3KHFU8PlJRhbRWsva0sTBilteZJHBbwY8vL/dAwXa5kGYm4dMehT3NugmmCccyiNIYDGSxq9mb87y7Cg0jcURmW4gOtmMl+FFt6c3Fu9ctjozxDq+mNWtS2RYwa5jC15bansxBn9nKatVZ2NIsqYNXBLp9AzZdQ4oukKkuAyY7CUJWqFxYpylRFazv1sb9upgHgXqqEfbEPL4j3XhHubobJKxnbmh+V9Z2YzWzRGEPoCdAAQYafPbi21qIjQGMEff8pD0UqJmkZskT5WY3g5JPZLNWXfYyXOk7SvvEz5Kcw27p6uzz1KrX7TJpr8uOM+FALfmUDegA=
